services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    container_name: weaviate
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.0
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      ENABLE_API_BASED_MODULES: "true"
      ENABLE_MODULES: "text2vec-transformers,text2vec-openai"
      # OPENAI_APIKEY:  ${OPENAI_APIKEY}
      CLUSTER_HOSTNAME: "node1"
      TRANSFORMERS_INFERENCE_API: http://text2vec-transformers:8080
  text2vec-transformers:
    container_name: text2vec-transformers
    # image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    image: semitechnologies/transformers-inference:qwen-qwen3-embedding-0.6b
    # environment:
      # ENABLE_CUDA: 0
volumes:
  weaviate_data:
